### ISSUE TITLE
https://packs.1qr.org/packages.json (HTTP/1.1 502 Bad Gateway)

### ISSUE THREAD

**Issue by ramires0826** [mopkob1/openvpntelegrambot#3]
During execution init.sh error 502 occurs

The "https://packs.1qr.org/packages.json" file could not be downloaded (HTTP/1.1 502 Bad Gateway)

**Comment by mopkob1** [comment]
@ramires0826, thank you for your issue.

Package source have changed, debugging mode now is off. Some warnings are fixed.
